### ISSUE TITLE
Clue - updateEnabledButtons() - enable/disable the makeAccusation button

### ISSUE THREAD

**Issue by zbialik** [zbialik/clue-less-ui#15]
enable/disable the makeAccusation button based on the player's state

**Comment by alex4287** [comment]
I did a pull request - hope I didn't botch the code. Let me know if so, Zach - and I'll fix it.

**Comment by zbialik** [comment]
@alex4287 I don't see your pull request

**Comment by alex4287** [comment]
It's up now - had a little hiccup there. Let me know if I need fix anything.
