### ISSUE TITLE
Stage Character Images

### ISSUE THREAD

**Issue by zbialik** [zbialik/clue-less-ui#2]
add character images (jpegs/pngs) to https://github.com/zbialik/clue-less-ui/tree/main/ui/src/assets/images/characters

**NOTE:** 
- these should all be the same since/format
- we will need a set of images for the suspect cards, and may want another for the character game pieces. lets just start with gathering the cards images.

for the cards, I think these would be good to cut/save as individual card images --> 
[suspect cards option 1](https://i.pinimg.com/originals/67/8f/f1/678ff16c22193edf60a9c61fbc3c09dd.jpg)
[suspect cards option 2](https://i.pinimg.com/originals/b9/09/a3/b909a32b4a56e0724bb982c4f04a6397.jpg)

**Comment by alex4287** [comment]
Apologies - I had already found these and cut them before I saw your comment in Github. I hope this design is okay. If not then no worries - just let me know and I'll re-cut the ones from your suggestion.


![GREEN](https://user-images.githubusercontent.com/40349336/115827403-18802900-a3c1-11eb-8351-acd6843bff79.jpg)
![WHITE](https://user-images.githubusercontent.com/40349336/115827419-1f0ea080-a3c1-11eb-87a8-3b06e58d6a78.jpg)
![SCARLETT](https://user-images.githubusercontent.com/40349336/115827424-1fa73700-a3c1-11eb-8278-c17230dff37d.jpg)
![PLUM](https://user-images.githubusercontent.com/40349336/115827425-1fa73700-a3c1-11eb-8751-a47c7426083a.jpg)
![PEACOCK](https://user-images.githubusercontent.com/40349336/115827426-1fa73700-a3c1-11eb-95e3-d20caea3a68d.jpg)
![MUSTARD](https://user-images.githubusercontent.com/40349336/115827431-203fcd80-a3c1-11eb-91d5-cd61f39fd641.jpg)

**Comment by zbialik** [comment]
> Apologies - I had already found these and cut them before I saw your comment in Github. I hope this design is okay. If not then no worries - just let me know and I'll re-cut the ones from your suggestion.

These are great and I like that they match the Room Cards
