### ISSUE TITLE
Stage Room Images

### ISSUE THREAD

**Issue by zbialik** [zbialik/clue-less-ui#3]
add room images (jpegs/pngs) to https://github.com/zbialik/clue-less-ui/tree/main/ui/src/assets/images/rooms

NOTE:
- these should all be the same since/format
- we may want a set for the game pieces and another set for the room cards

for the cards, I think these would be good to cut/save as individual card images --> 
[room cards option 1](https://i.pinimg.com/originals/db/8d/ef/db8def5f54ebec556d15e6a83c293b9e.jpg)
[room cards option 2](https://i.pinimg.com/originals/cb/a3/b0/cba3b05225df33943213b09f95ca3fee.jpg)

**Comment by alex4287** [comment]
![BALLROOM](https://user-images.githubusercontent.com/40349336/115826994-8d9f2e80-a3c0-11eb-9277-3fd604f2b7ac.jpg)
![DINING](https://user-images.githubusercontent.com/40349336/115827001-8f68f200-a3c0-11eb-8f70-01d24afbcfea.jpg)
![LOUNGE](https://user-images.githubusercontent.com/40349336/115827004-909a1f00-a3c0-11eb-856d-185b462ae9b4.jpg)
![BILLIARD](https://user-images.githubusercontent.com/40349336/115827007-9132b580-a3c0-11eb-8518-767e05b9b364.jpg)
![LIBRARY](https://user-images.githubusercontent.com/40349336/115827010-91cb4c00-a3c0-11eb-85e2-1e07b41f5ce6.jpg)
![CONSERVATORY](https://user-images.githubusercontent.com/40349336/115827013-9263e280-a3c0-11eb-8da4-acb92f5f081a.jpg)
![HALL](https://user-images.githubusercontent.com/40349336/115827015-92fc7900-a3c0-11eb-87af-4c1643b82b18.jpg)
![KITCHEN](https://user-images.githubusercontent.com/40349336/115827016-92fc7900-a3c0-11eb-91eb-49ec34204999.jpg)
![STUDY](https://user-images.githubusercontent.com/40349336/115827017-93950f80-a3c0-11eb-9b37-c48ce8e780f6.jpg)

I uploaded these to the folder to be merged if okay.
