### ISSUE TITLE
Stage Weapon Images

### ISSUE THREAD

**Issue by zbialik** [zbialik/clue-less-ui#4]
add weapon images (jpegs/pngs) to https://github.com/zbialik/clue-less-ui/tree/main/ui/src/assets/images/weapons

NOTE:
- these should all be the same since/format
- only need 1 set for weapon cards

for the cards, I think these would be good to cut/save as individual card images --> 
[weapon cards option 1](https://i.pinimg.com/originals/55/87/54/558754b90ff861b967fa57bd5cf6d6a9.jpg)
[weapon cards option 2](https://i.pinimg.com/originals/b5/f4/8e/b5f48e3b44b6e328bb005befe04bed04.jpg)
[weapon cards option 3](https://i.pinimg.com/originals/89/65/19/8965190f83506f6d5b34c84008650b1e.jpg)

**Comment by alex4287** [comment]
I added these to the folder already in a separate branch - to be merged. 
I can photoshop the ' Spanner ' --> Wrench and re-upload to the branch if that is preferred. 

![SPANNER](https://user-images.githubusercontent.com/40349336/115827198-d0f99d00-a3c0-11eb-8560-5ef7a65cf64b.jpg)
![ROPE](https://user-images.githubusercontent.com/40349336/115827199-d1923380-a3c0-11eb-8e42-0411b9eb2b12.jpg)
![LEADPIPING](https://user-images.githubusercontent.com/40349336/115827200-d1923380-a3c0-11eb-90d5-7429b1404264.jpg)
![DAGGER](https://user-images.githubusercontent.com/40349336/115827201-d1923380-a3c0-11eb-8674-b007d8838f7f.jpg)
![CANDLESTICK](https://user-images.githubusercontent.com/40349336/115827202-d22aca00-a3c0-11eb-9c92-626f6b8dea8c.jpg)
![REVOLVER](https://user-images.githubusercontent.com/40349336/115827203-d22aca00-a3c0-11eb-8b8d-d5bba12eea2d.jpg)

**Comment by zbialik** [comment]
> I added these to the folder already in a separate branch - to be merged.
> I can photoshop the ' Spanner ' --> Wrench and re-upload to the branch if that is preferred.

Yeah idk what a 'spanner' is but think thats kinda confusing. If you can photoshop it that'd be great.

**Comment by alex4287** [comment]
Done. 
![WRENCH](https://user-images.githubusercontent.com/40349336/115923271-d5f73480-a432-11eb-9d87-4be71e00e07b.jpg)
